name: CD
on:
  push:
    tags: 
      - 'v*'
env:
  NODE_VERSION: 22.0.0
  PNPM_VERSION: 8.13.1
jobs:
  ci:
    uses: './.github/workflows/ci.yml'
  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'main') == false
        run: exit 0
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Create Release 
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: 'dist/*'
      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}